#!/usr/bin/env node

'use strict';

let args = process.argv.slice(2);

const Tree = require('./bst');
const tree = new Tree();

args.forEach(arg => tree.add(parseInt(arg, 10)));

console.log(JSON.stringify(tree, null, 2));
